### PR TITLE
Add scripts for installing golang and moving projects into the go workspace

### PR DESCRIPTION
**Pull request by burnsed**
https://clever.atlassian.net/browse/INFRA-2093

These scripts implement the following common CircleCI patterns:

**golang-install** 
```
    - mkdir -p download
    - test -e download/$GODIST || curl -o download/$GODIST https://storage.googleapis.com/golang/$GODIST
    - sudo rm -rf /usr/local/go
    - sudo tar -C /usr/local -xzf download/$GODIST
```

now can be run as `./ci-scripts/golang-install $GODIST`

**golang-move-project**
```
    - mkdir -p $HOME/.go_workspace/src/github.com/$CIRCLE_PROJECT_USERNAME
    - rm -rf $HOME/.go_workspace/src/github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME || true
    - mv $HOME/$CIRCLE_PROJECT_REPONAME $HOME/.go_workspace/src/github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
    - mkdir $HOME/$CIRCLE_PROJECT_REPONAME
```

 now can be run as `./ci-scripts/golang-move-project`

An example of a circleci.yaml we would like to simplify can be seen here:
https://github.com/Clever/wag-test/blob/circleci/circle.yml

### CODE REVIEW

**Comment by jiancheung** [comment]
Could you provide more context for this PR? jira ticket? explanation of why this is necessary in circleci world?

**Comment by burnsed** [comment]
updated the description. Before we start converting repos to circleci we want to make sure that the circle.yml files are as simple as possible. This is a first step to reducing the amount of code we need to copy and paste between them.

**Comment by burnsed** [comment]
See also https://github.com/Clever/wag-test/pull/1

**Comment by jiancheung** [comment]
lgtm!

**Pull request merged**
